version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
  browser-tools: circleci/browser-tools@1.4.0
jobs:
  build:
    docker:
      - image: "cimg/node:14.15"
    steps:
      # install node and checkout code
      - node/install:
          node-version: '14.15'                     
      - checkout
      # Use root level package.json to install dependencies in the frontend app
      - run:
          name: Install Front-End Dependencies
          command: |
            npm run frontend:install
      # Install dependencies in the the backend API          
      - run:
          name: Install API Dependencies
          command: |
           npm run backend:install
      # Lint the frontend
      - run:
          name: Front-End Lint
          command: |
            npm run frontend:lint
      # Build the frontend app
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      # Build the backend API      
      - run:
          name: API Build
          command: |
            npm run backend:build
  # deploy step will run only after manual approval
  deploy:
    docker:
      - image: "cimg/base:stable"
      # more setup needed for aws, node, elastic beanstalk
    steps:
      - node/install:
          node-version: '14.15' 
      - aws-cli/setup
      - eb/setup
      - checkout
      - run:
          name: Deploy App
          # Install, build, deploy in both apps
          command: |
            npm run deploy
            
workflows:
  udagram:
    jobs:
      - build
      - deploy:
        filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - build